import fs from "fs";
import { ethers } from "ethers";
import { poseidon2Hash } from "@aztec/bb.js";

// ---------- utils ----------
function bytes32FromBigint(x) {
  let h = x.toString(16);
  if (h.length > 64) throw new Error("Too big for bytes32");
  return "0x" + h.padStart(64, "0");
}

function bytes32FromBuf(buf) {
  if (buf.length !== 32) throw new Error("expected 32 bytes");
  return "0x" + Buffer.from(buf).toString("hex");
}

function readPublicInputsWords(path) {
  const b = fs.readFileSync(path);
  if (b.length % 32 !== 0) throw new Error("public_inputs not multiple of 32 bytes");
  const n = b.length / 32;
  const words = [];
  for (let i = 0; i < n; i++) {
    words.push(bytes32FromBuf(b.subarray(i * 32, (i + 1) * 32)));
  }
  return words;
}

// Poseidon2 BN254 hash_2 equivalent
function poseidon2_2(a, b) {
  // bb.js expects Buffers? We'll feed BigInt -> returns BigInt.
  // poseidon2Hash takes array of BigInt
  return poseidon2Hash([a, b]);
}

function computeEntry(value, holder, random, nullifier) {
  // poseidon2([poseidon2([value, holder]), poseidon2([random, nullifier])])
  const left = poseidon2_2(value, holder);
  const right = poseidon2_2(random, nullifier);
  return poseidon2_2(left, right);
}

// Build binary merkle root with Poseidon2, fixed depth = 10
function merkleRootBinaryPoseidon2(leaf, siblings, indices, depth = 10) {
  let cur = leaf;
  for (let i = 0; i < depth; i++) {
    const sib = siblings[i];
    const idx = indices[i]; // 0 => leaf is left, 1 => leaf is right
    cur = idx === 0 ? poseidon2_2(cur, sib) : poseidon2_2(sib, cur);
  }
  return cur;
}

// Precompute zero hashes for Poseidon2 tree (depth=10)
function buildZeroSiblings(depth = 10) {
  const zeros = [];
  // Usually zero leaf = 0
  let z = 0n;
  for (let i = 0; i < depth; i++) {
    zeros.push(z);
    z = poseidon2_2(z, z);
  }
  return zeros; // siblings at each level for an empty tree at position 0
}

// ---------- main ----------
async function main() {
  const RPC = process.env.MONAD_RPC;
  const PK = process.env.PRIVATE_KEY;
  const POOL = process.env.POOL_ADDRESS;

  if (!RPC || !PK || !POOL) {
    throw new Error("Set MONAD_RPC, PRIVATE_KEY, POOL_ADDRESS env vars");
  }

  const poolAbi = JSON.parse(fs.readFileSync("./scripts/abi/ShieldedPool.abi.json", "utf8"));
  const provider = new ethers.JsonRpcProvider(RPC);
  const wallet = new ethers.Wallet(PK, provider);
  const pool = new ethers.Contract(POOL, poolAbi, wallet);

  // 1) Read proof + public inputs generated by your bb pipeline
  const proofHex = fs.readFileSync("./proofs/with_foundry.proof", "utf8").trim();
  if (!proofHex.startsWith("0x")) throw new Error("proof must start with 0x");

  const pubWords = readPublicInputsWords("./proofs/public_inputs");
  // Expected order (your Noir circuit):
  // [0]=new_commitment, [1]=nullifier_in, [2]=merkle_proof_length, [3]=expected_merkle_root
  if (pubWords.length < 4) throw new Error(`expected >=4 public inputs, got ${pubWords.length}`);

  const newCommitment = pubWords[0];
  const nullifierIn = pubWords[1];
  const merkleProofLengthWord = pubWords[2];
  const expectedRoot = pubWords[3];

  const merkleProofLength = Number(BigInt(merkleProofLengthWord)); // uint32
  console.log("newCommitment:", newCommitment);
  console.log("nullifierIn:  ", nullifierIn);
  console.log("proofLen:     ", merkleProofLength);
  console.log("expectedRoot: ", expectedRoot);

  // 2) (Optional) Build root offchain with a simple empty-tree sibling set for demo
  // If your proof uses real siblings/indices from your actual tree state, you should compute that same root.
  // For MVP: we just show how to compute an empty-tree root path (index=0 all the way).
  const depth = 10;
  const zeroSiblings = buildZeroSiblings(depth);
  const indices = Array(depth).fill(0);

  // Example: if you want to reproduce entry_in, you’d need the same private inputs used in Prover.toml.
  // We'll skip recomputing entry_in here because proof already has expectedRoot; we just show the mechanism:
  const demoLeaf = 0n;
  const demoRoot = merkleRootBinaryPoseidon2(demoLeaf, zeroSiblings, indices, depth);
  console.log("demo empty-tree root:", bytes32FromBigint(demoRoot));

  // 3) Register root onchain (idempotent pattern)
  // Your contract reverts if already known, so we try/catch.
  try {
    const tx = await pool.registerRoot(expectedRoot);
    console.log("registerRoot tx:", tx.hash);
    await tx.wait();
    console.log("root registered");
  } catch (e) {
    console.log("registerRoot skipped (maybe already known):", e?.shortMessage ?? e?.message ?? e);
  }

  // 4) Submit transfer intent
  const tx2 = await pool.transferIntent(
    expectedRoot,
    nullifierIn,
    merkleProofLength,
    newCommitment,
    proofHex
  );
  console.log("transferIntent tx:", tx2.hash);
  await tx2.wait();
  console.log("transferIntent settled ✅");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
